{{- if .Values.agent.enabled -}}
{{- if (and (not (empty .Values.agent.tlsFiles.cert) ) (not (empty .Values.agent.tlsFiles.key) ) ) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "kiam.fullname" . }}-agent
type: Opaque
data:
{{ toYaml .Values.agent.tlsFiles | indent 2 }}
{{- end }}
{{- end }}
