{{- if .Values.server.enabled -}}
{{- if (and (not (empty .Values.server.tlsFiles.cert) ) (not (empty .Values.server.tlsFiles.key) ) ) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "kiam.fullname" . }}-server
type: Opaque
data:
{{ toYaml .Values.server.tlsFiles | indent 2 }}
{{- end }}
{{- end }}
